### ISSUE TITLE
AttributeError: 'TemplateNode' object has no attribute 'fast_template_instance'

### ISSUE THREAD

**Issue by bigsnarfdude** [williballenthin/python-evtx#10]
I was following the example on a test file and the evtxinfo.py and evtxdump.py worked.
An error in evtxtemplates.py was found. Here is the output from the three scripts:

```
~/Downloads/python-evtx/scripts(master) $python evtxinfo.py ~/Desktop/webpub/system_event_log.evtx
Information from file header:
Format version  : 3.1
Flags           : 0x00000000
File is         : clean
Log is full     : no
Current chunk   : 0 of 1
Oldest chunk    : 1
Next record#    : 106
Check sum       : pass

Information from chunks:
  Chunk file (first/last)     log (first/last)      Header Data
- ----- --------------------- --------------------- ------ ------
*     1          1       105           1       105   pass   pass






~/Downloads/python-evtx/scripts(master) $python evtxtemplates.py ~/Desktop/webpub/system_event_log.evtx
Template {002acd1a-3b0d-62e5-b04f-65ee3cecc038} at chunk 0, offset 0x2486
Traceback (most recent call last):
  File "evtxtemplates.py", line 42, in <module>
    main()
  File "evtxtemplates.py", line 39, in main
    print evtx_template_readable_view(template)
  File "/Library/Python/2.7/site-packages/Evtx/Views.py", line 266, in evtx_template_readable_view
    template_instance = root_node.fast_template_instance()
AttributeError: 'TemplateNode' object has no attribute 'fast_template_instance'





~/Downloads/python-evtx/scripts(master) $python evtxdump.py ~/Desktop/webpub/system_event_log.evtx
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<Events>
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event"><System><Provider Name="EventLog"></Provider>
<EventID Qualifiers="32768">6008</EventID>
<Level>2</Level>
<Task>0</Task>
<Keywords>0x0080000000000000</Keywords>
<TimeCreated SystemTime="2014-03-09 09:05:11"></TimeCreated>
<EventRecordID>81252</EventRecordID>
<Channel>System</Channel> 
```

**Comment by williballenthin** [comment]
should be fix in 1d869c68a31ec9b3a9c6626bc1c15ec459c8ac89, which will be merged very shortly
