### ISSUE TITLE
AttributeError: 'str' object has no attribute 'fomrat'

### ISSUE THREAD

**Issue by cbitterfield** [williballenthin/python-evtx#22]
I am trying to parse some windows logs in "evt" format. 
It does a pretty good job of parsing until this point:

```
Traceback (most recent call last):
  File "evtxdump.py", line 49, in <module>
    main()
  File "evtxdump.py", line 44, in main
    for xml, record in evtx_file_xml_view(fh):
  File "build/bdist.macosx-10.11-intel/egg/Evtx/Views.py", line 204, in evtx_file_xml_view
  File "build/bdist.macosx-10.11-intel/egg/Evtx/Views.py", line 155, in _build_record_xml
  File "build/bdist.macosx-10.11-intel/egg/Evtx/Views.py", line 149, in rec
  File "build/bdist.macosx-10.11-intel/egg/Evtx/Views.py", line 145, in rec
  File "build/bdist.macosx-10.11-intel/egg/Evtx/BinaryParser.py", line 112, in __call__
  File "build/bdist.macosx-10.11-intel/egg/Evtx/Nodes.py", line 1016, in fast_substitutions
AttributeError: 'str' object has no attribute 'fomrat'
```

```
bash-3.2# python --version
Python 2.7.10
```
```
evt
v0.3.2
```

**Comment by thomasRousseau** [comment]
My fault, typo fixed, and PR pushed. Should be merged this afternoon.
You can manually edit Evtx/Nodes.py (fomrat -> format) in the meantime.
Sorry again

**Comment by williballenthin** [comment]
fixed is merged.
